name: flutkit
description: Una aplicaciÃ³n de la UPSA.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0
versionCode: 6

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  shared_preferences: ^2.0.5
  google_fonts: ^4.0.4


  # Icons
  material_design_icons_flutter: 5.0.6996
  flutter_feather_icons: ^2.0.0+1

  #(Syncfusion Flutter packages - Charts, Calendar, ETC.)
  syncfusion_flutter_core: ^20.1.56
  syncfusion_flutter_calendar: ^20.1.56
  syncfusion_flutter_datepicker: ^20.1.56
  syncfusion_flutter_sliders: ^20.1.56
  syncfusion_flutter_charts: ^20.1.56
  syncfusion_flutter_gauges: ^20.1.56

  # Other
  google_maps_flutter: ^2.0.3
  shimmer: ^2.0.0
  url_launcher: ^6.2.6
  intl: ^0.18.0
  rive: ^0.13.12
  flare_flutter: ^3.0.2
  flutter_intro: ^2.3.1
  image_picker: ^1.0.2
  #  flutx:
  #    path: ../flutx
  boxicons: ^2.1.3
  #  flutx: ^0.2.0-rc.2
  get: ^4.6.5
  curved_navigation_bar: ^1.0.3
  flashy_tab_bar2: ^0.0.6
  blur: ^3.1.0
#  google_mobile_ads: ^3.0.0
  flutter_blurhash: ^0.7.0 
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  flutter_dotenv: ^5.1.0
  flutter_otp_text_field: ^1.1.3+2
  http: ^1.2.2
  package_info: ^2.0.2
  cached_network_image: ^3.3.1
  barcode_widget: ^2.0.4
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.7.0
  multi_dropdown: ^2.1.0
  lucide_icons: ^0.257.0
  table_calendar: ^3.0.9
  #youtube_player_flutter: ^9.0.3
  photo_view: ^0.15.0
  dio: ^5.4.3+1
  flutter_app_info: ^1.1.2
  search_choices: ^2.2.7
  video_player: ^2.9.1
  youtube_player_iframe: ^5.1.2
  firebase_analytics: ^10.10.7
  mobile_scanner: ^5.1.1
#  flutx: ^0.2.0-rc.1
#  flutx: ^0.1.2

#module:
#  androidX: true

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: InterTight
      fonts:
        - asset: lib/custom/assets/fonts/InterTight-Black.ttf
          weight: 900
        - asset: lib/custom/assets/fonts/InterTight-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-Bold.ttf
          weight: 700
        - asset: lib/custom/assets/fonts/InterTight-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-ExtraBold.ttf
          weight: 800
        - asset: lib/custom/assets/fonts/InterTight-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-ExtraLight.ttf
          weight: 200
        - asset: lib/custom/assets/fonts/InterTight-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-Italic.ttf
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-Light.ttf
          weight: 300
        - asset: lib/custom/assets/fonts/InterTight-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: lib/custom/assets/fonts/InterTight-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-Regular.ttf
        - asset: lib/custom/assets/fonts/InterTight-SemiBold.ttf
          weight: 600
        - asset: lib/custom/assets/fonts/InterTight-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/custom/assets/fonts/InterTight-Thin.ttf
          weight: 100
        - asset: lib/custom/assets/fonts/InterTight-ThinItalic.ttf
          weight: 100
          style: italic
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - .env

    - lib/custom/assets/images/
    
    # Languages
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

